name: MavenPublish

on:
  push:
    branches:
      - "2020.**"
      - "2021.**"
      - "2022.**"
  # 定时执行，北京时间10点执行一次，UTC时间2点即北京时间10点
#  schedule:
#    - cron: '0 2 * * *'

env:
  APPLICATION_NAME: "starfish"
#  APPLICATION_VERSION: "1.0.0"
#  APPLICATION_ENV: "dev"

jobs:
  MavenDeploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Install and Publish to GitHub Packages
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: mvn --batch-mode --update-snapshots clean deploy -Dmaven.test.skip=true

#  - name: Build With Maven
#      run: mvn --batch-mode --update-snapshots clean package -Dmaven.test.skip=true
#      env:
#        MAVEN_PASSWORD: ${{ secrets.PACKAGES_TOKEN }}

#      - name: Deploy
#        uses: easingthemes/ssh-deploy@v2.2.11
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.TENCENT_SERVER_PRIVATE_KEY }}
#          ARGS: "-rltgoDzvO --delete"
#          SOURCE: "target/starfish-1.0.0-SNAPSHOT.jar"
#          REMOTE_HOST: "101.34.149.151"
#          REMOTE_USER: "root"
#          TARGET: "/opt/starfish"
